language:
    go

go:
    - tip

install:
    - go get gopkg.in/check.v1
    - go get code.google.com/p/go.tools/cmd/cover
    - go get github.com/mattn/goveralls

script:
    - go test -covermode=count -coverprofile=profile.cov

after_script:
    - $HOME/gopath/bin/goveralls -coverprofile=profile.cov -service=travis-ci